### ISSUE TITLE
 Redeploying "production" with new variables GraphQL query failed with 1 errors: Not Authorized

### ISSUE THREAD

**Issue by boertel** [railwayapp/cli#140]
When trying to set an environment variable inside a github action I'm getting the following error:
```
Run npx railway variables set HELLO="world"
==> Updated HELLO for "production"
HELLO: world

🚝 Redeploying "production" with new variables
🚅 Redeploying "production" with new variables
🚄 Redeploying "production" with new variables
🚇 Redeploying "production" with new variables GraphQL query failed with 1 errors: Not Authorized
```

The _weird_ part is that the variable is set on the app but the failure makes the github actions fails and stops. 

Here is a github action to replicate the issue:
```yaml
name: Railway
on: push
jobs:
  deploy:
    runs-on: ubuntu-18.04
    env:
      RAILWAY_TOKEN: ${{secrets.RAILWAY_TOKEN}}
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '15'
      - run: npm install @railway/cli@0.2.35 -g
      - run: npx railway variables set HELLO="world"
```
