### ISSUE TITLE
Workflow seems to hang

### ISSUE THREAD

**Issue by geekyouth** [railwayapp/cli#292]
```yaml
name: 😊Deploy to Railway after release

on:
  release:
    types: [ created ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install Railway
        run: npm i -g @railway/cli
      - name: Deploy
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN_GITHUB }}

```

![image](https://user-images.githubusercontent.com/12899262/207295571-30598b6f-7d11-447b-af7a-2a45875e8fb7.png)

and the service has run success on railway dashboard by above workflow.

but way the workflow is always hanging???

**Comment by zanminkian** [comment]
I face the same problem.
```yml
name: Railway cli

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
jobs:
  railway:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Install Railway CLI
        run: curl -fsSL https://railway.app/install.sh | sh
      -
        name: Deploy to Railway
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
```
