### ISSUE TITLE
`RAILWAY_DOCKERFILE_PATH ` not work

### ISSUE THREAD

**Issue by zanminkian** [railwayapp/cli#300]
My github workflow looks like this:
```yaml
name: Railway

on:
  push:
    branches:
      - master
    paths:
      - Dockerfile.railway
jobs:
  railway:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Railway CLI
        run: curl -fsSL https://railway.app/install.sh | sh
      - name: Deploy to Railway
        run: railway up --detach
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          RAILWAY_DOCKERFILE_PATH: Dockerfile.railway
```
The building error looks like this:
<img width="636" alt="image" src="https://user-images.githubusercontent.com/35495628/218340036-f60c606d-3e06-4c7a-919a-3f9cacff2902.png">
