### ISSUE TITLE
`railway up` failing on GitHub Actions since 3.0.12

### ISSUE THREAD

**Issue by endofhome** [railwayapp/cli#382]
I'm running `railway up` on GitHub Actions from the root directory of my project, and supplying a valid `RAILWAY_TOKEN` environment variable.

Since the release of CLI 3.0.12 this is failing like so:

```
Run railway up
  railway up
  shell: /usr/bin/bash -e {0}
  env:
    RAILWAY_TOKEN: ***
Error: No linked project found
Error: Process completed with exit code 1.
```

Rolling back to 3.0.8 resolves the issue.

**Comment by exilvm** [comment]
I can confirm that installing the CLI using `npm i -g @railway/cli@3.0.8` fixes the issue.

**Comment by flpnascto** [comment]
Same problem here:

Github action:
```yml
      - name: Deploy to Railway - Front-end
        run: railway up --detach -s front-end
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
```
Action Results
```sh
1 Railway CLI install info
2   /usr/local/bin/railway --version
3   railwayapp 3.0.12
```

```sh
1 Run railway up --detach -s front-end
2  railway up --detach -s front-end
3  shell: /usr/bin/bash -e {0}
4  env:
5    RAILWAY_TOKEN: ***
6 Error: No linked project found
7 Error: Process completed with exit code [1](
```

**Comment by nickmacavoy** [comment]
I took some cues from the Discord channel – you have to link the project first now with the new CLI. Add this step before your `railway up` step:

```
      - name: Link to Railway project
        run: railway link --environment YOUR_RAILWAY_ENVIRONMENT YOUR_PROJECT_ID
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_DEPLOY_TOKEN }}
```
