### ISSUE TITLE
railway down not authorized github actions

### ISSUE THREAD

**Issue by notAperson535** [railwayapp/cli#425]
Hello, I made a script that takes down the railway deployment on weekends and turns it back on during the week, but i have been encountering this error:
```
Run railway down -y
Unauthorized. Please login with `railway login`
Error: Process completed with exit code 1.
```

`railway up` works perfectly, just not `railway down`

here is my github action workflow file:
```
name: Stop deployment on saturdays

on:
    schedule: 
    - cron: "0 0 * * 6"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node 18
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Deploy
        run: railway down -y
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
```
