### ISSUE TITLE
service account key is ignored

### ISSUE THREAD

**Issue by doichev-kostia** [railwayapp/cli#471]
Hey there!

I'm not sure whether that is a CLI issue, but it's surely an inconvenience I'd like to ask for help about. I'm trying to deploy the project which uses the Dockerfile as the build system. The issue occurs when I'm trying to copy the GCP service-account.json file to the image. By default, it's included in `.gitignore` and not committed in the repo. However, this file is crucial for the APP to work, so my idea was to pull this file from the GCP secret manager using their CLI in the GitHub actions runner and then let the docker copy it. Although the file exists locally, the `railway up` command ignores it

The GitHub actions workflow is ideally the following
```yaml
name: deploy

on:
  workflow_dispatch:
  release:
    types: [ created ]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
          credentials_file_path: ./credentials.json

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: Set credentials
        run: gcloud auth login --cred-file=${{steps.auth.outputs.credentials_file_path}}

      - name: Pull service account key
        run: |
          gcloud secrets versions access latest --project=${{ secrets.GCP_PROJECT_ID }} --secret=${{ secrets.SERVICE_ACCOUNT_SECRET_NAME }} > ./apps/api/service-account.json
          
          # run the railway up command
```

What I see from the railway up command is the following
```
[runner 8/9] COPY --from=installer --chown=node:node /app/apps/api/service-account.json /trainly/apps/api/service-account.json:
-----

Dockerfile:47
-------------------
45 |     COPY --from=installer --chown=node:node /app/packages $APP_HOME/packages
46 |     COPY --from=installer --chown=node:node /app/apps/api/app-config.json5 $FASTIFY_CONFIG
47 | >>> COPY --from=installer --chown=node:node /app/apps/api/service-account.json $GOOGLE_APPLICATION_CREDENTIALS
48 |
49 |     USER node
-------------------
ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref ee8ca8ee-734c-4262-be2f-c571f3dbeead::obclqkrjobxb7pzmv4nyzldyd: "/app/apps/api/service-account.json": not found
```

Even when I try to disable the ignore in `.railwayignore` file
```
!service-account.json
```

It still omits that file

When I just run `docker build` locally, the file is included
