### ISSUE TITLE
Unauthorized. Please login with `railway login`

### ISSUE THREAD

**Issue by dwilt** [railwayapp/cli#617]
I'm trying to use your base example in a Github action. Here's what I have:

```
  test-auth:
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - run: railway init
```
But I get this error:
```
Unauthorized. Please login with `railway login`
```
However, if I change the `run` to be ` - run: railway status`, I get:
```
Project: humble-expression
Environment: production
Service: None
```
So, clearly it's using my token cause it knows exactly what project I set the token in. I'm guessing I wouldn't be able to access the project without being authenticated but I guess I'm wrong in that. What I don't understand is how to login from the CLI -- I need to create a project and add services to it to create Github branch-specific deployments. Am I going about this wrong?
